name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # or 16 or any LTS version

      - name: Install dependencies
        run: npm install
        working-directory: node-app

      - name: Run test
        working-directory: node-app
        run: npm test